version: "3.9"

services:
  rathena:
    build: ./rathena
    container_name: rathena
    depends_on:
      - db
    environment:
      - DB_HOST=db
    ports:
      - "6900:6900"
      - "6121:6121"
      - "5121:5121"
    volumes:
      - ./rathena:/opt/rathena
    networks:
      - ragnarok-online

  db:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ragnarok
      MYSQL_DATABASE: ragnarok
      MYSQL_USER: ragnarok
      MYSQL_PASSWORD: ragnarok
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ragnarok-online

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ragnarok
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - ragnarok-online

  fluxcp:
    build: ./fluxcp
    container_name: fluxcp
    ports:
      - "80:80"
    volumes:
      - ./fluxcp:/var/www/html
    depends_on:
      - db
    networks:
      - ragnarok-online

volumes:
  db_data:

networks:
  ragnarok-online:
