version: "3.9"

services:
  db:
    image: mariadb:10.6
    container_name: ragnarok-online-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ragnarok}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ragnarok}
      MYSQL_USER: ${MYSQL_USER:-ragnarok}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ragnarok}
    volumes:
      - ${DB_VOLUME:-./mariadb}:/var/lib/mysql
    networks:
      - ragnarok-online

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ragnarok-online-phpmyadmin
    environment:
      PMA_HOST: ${MYSQL_HOST:-db}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ragnarok}
    ports:
      - "${PHPMYADMIN_PORT:-5124}:80"
    depends_on:
      - db
    networks:
      - ragnarok-online

  fluxcp:
    image: fluxcp:0.0.1
    container_name: ragnarok-online-fluxcp
    ports:
      - "${FLUXCP_PORT:-5123}:80"
    environment:
      MYSQL_HOST: ${MYSQL_HOST:-db}
      MYSQL_DB: ${MYSQL_DATABASE:-ragnarok}
      MYSQL_USER: ${MYSQL_USER:-ragnarok}
      MYSQL_PWD: ${MYSQL_PASSWORD:-ragnarok}
      FLUXCP_HOST: ${FLUXCP_HOST:-127.0.0.1}
      FLUXCP_INSTALLER_PASSWORD: ${FLUXCP_INSTALLER_PASSWORD:-ragnarok}
    depends_on:
      - db
      - phpmyadmin
    volumes:
      - ${FLUXCP_CACHE:-./fluxcp/cache}:/cache
    networks:
      - ragnarok-online

  rathena:
    image: rathena:0.0.1
    container_name: ragnarok-online-rathena
    depends_on:
      - fluxcp
      - phpmyadmin
      - db
    environment:
      MYSQL_HOST: ${MYSQL_HOST:-db}
      MYSQL_DB: ${MYSQL_DATABASE:-ragnarok}
      MYSQL_USER: ${MYSQL_USER:-ragnarok}
      MYSQL_PWD: ${MYSQL_PASSWORD:-ragnarok}
      MYSQL_DROP_DB: ${MYSQL_DROP_DB:-0}
      BIND_IP: ${BIND_IP:-0.0.0.0}

      SET_INTERSRV_USERID: ${SET_INTERSRV_USERID:-ragnarok}
      SET_INTERSRV_PASSWD: ${SET_INTERSRV_PASSWD:-ragnarok}

      SET_CHAR_TO_LOGIN_IP: ${SET_CHAR_TO_LOGIN_IP:-127.0.0.1}
      SET_CHAR_PUBLIC_IP: ${SET_CHAR_PUBLIC_IP:-127.0.0.1}
      SET_MAP_TO_CHAR_IP: ${SET_MAP_TO_CHAR_IP:-127.0.0.1}
      SET_MAP_PUBLIC_IP: ${SET_MAP_PUBLIC_IP:-127.0.0.1}

      SET_SERVER_NAME: ${SET_SERVER_NAME:-TestServer}
      RATHENA_PACKETVER: ${RATHENA_PACKETVER:-20220406}

      RATE_BASE_EXP: ${RATE_BASE_EXP:-100}
      RATE_JOB_EXP: ${RATE_JOB_EXP:-100}
      ENABLE_MULTI_LEVEL_UP: ${ENABLE_MULTI_LEVEL_UP:-1}
      RATE_ITEM_DROP_COMMON: ${RATE_ITEM_DROP_COMMON:-100}
      RATE_ITEM_DROP_HEAL: ${RATE_ITEM_DROP_HEAL:-100}
      RATE_ITEM_DROP_USABLE: ${RATE_ITEM_DROP_USABLE:-100}
      RATE_ITEM_DROP_EQUIP: ${RATE_ITEM_DROP_EQUIP:-50}
      RATE_ITEM_DROP_CARD: ${RATE_ITEM_DROP_CARD:-1}
      RATE_ITEM_DROP_MISC: ${RATE_ITEM_DROP_MISC:-50}
      RATE_ITEM_DROP_TREASURE: ${RATE_ITEM_DROP_TREASURE:-20}
    ports:
      - "${PORT_LOGIN:-6900}:6900"
      - "${PORT_CHAR:-6121}:6121"
      - "${PORT_MAP:-5121}:5121"
      - "${PORT_STATS:-5122}:8888"
    volumes:
      - ${RATHENA_CACHE:-./rathena/cache}:/cache
    networks:
      - ragnarok-online

volumes:
  db_data:

networks:
  ragnarok-online:
    driver: bridge